### ISSUE TITLE
create spreadsheet view of FH users and expiration dates

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghostconfig#11]
We'll do documentation in [here](https://docs.google.com/spreadsheets/d/1NVa_LGKFOFXomUDzRAFbKNNF5O62p0Q6iWqcSLmaUUw/edit?gid=0#gid=0) on Thursday. I recall that you have this documented from all Ghost admin tending this March, but we all need a view on it. Feel free to reshape that simple-dumb sheet however.

**Comment by unitof** [comment]
Related to https://github.com/yescomment/bh-flaminghydra-ghosttheme/issues/82

**Comment by unitof** [comment]
Source of truth for expiration dates is https://docs.google.com/spreadsheets/d/1kRzxXjk_dnhFs4CVqflhEfeL0ILBjXaRpy4e2BoajCo/edit?gid=0#gid=0&range=G:G.

We still have yet to write a script to add expiration dates to all FH users: https://github.com/yescomment/bh-flaminghydra-ghosttheme/issues/82

**Comment by unitof** [comment]
Created a new pivot table to track expiration cohorts by tier & expiration date: https://docs.google.com/spreadsheets/d/1kRzxXjk_dnhFs4CVqflhEfeL0ILBjXaRpy4e2BoajCo/edit?gid=901153361#gid=901153361 (`Comp Expiration Groups` sheet)
