### ISSUE TITLE
add Shirley to recipients of fake.flaminghydra.com emaiils

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/bh-flaminghydra-ghostconfig#6]
Please add shirley@flaminghydra.com so she can setup any contributors. This can happen next week, is fine. I think this is the correct repo to remember these things.

**Comment by unitof** [comment]
Add or replace you?

**Comment by davidmooreppf** [comment]
oh replace is fine

**Comment by unitof** [comment]
<img width="1117" alt="24853" src="https://github.com/yescomment/bh-flaminghydra-ghostconfig/assets/2448782/8ab974cb-8d63-4b2f-b7d9-a4150bd83f32">
